/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Borrow extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form Borrow
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Borrow() {
        initComponents();
          conn=DBConnect.connect();
        autoId();
       /*  String btype=txtbtype.getText();
         
       if( btype.equals("Issue"))
       {
        LocalDate today=LocalDate.now();
        LocalDate reday=today.plus(10,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtredate.setText(reday.toString());
        
        
            
        }
       else
       {
           LocalDate today=LocalDate.now();
        LocalDate reday=today.plus(0,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtredate.setText(reday.toString());
         
       }
        tablelord();*/
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtmtype = new javax.swing.JTextField();
        txtbid = new javax.swing.JTextField();
        txtbname = new javax.swing.JTextField();
        txtbtype = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtrno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtidate = new javax.swing.JTextField();
        txtredate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllend = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 680));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 660));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 240));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 340, 240));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 320, 310));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 700, 60));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel7.setText("Member ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 130, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel8.setText("Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setText("Member Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel10.setText("Book ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 110, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setText("Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 100, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setText("Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 90, -1));

        txtmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmidKeyReleased(evt);
            }
        });
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, -1));
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        txtmtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmtypeActionPerformed(evt);
            }
        });
        jPanel1.add(txtmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, -1));

        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 150, -1));
        jPanel1.add(txtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, -1));
        jPanel1.add(txtbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, -1));

        jLabel13.setText("Issue Date");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel14.setText("Return Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        jButton2.setText("Issue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));
        jPanel1.add(txtrno, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 160, -1));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1030, 310));
        jPanel1.add(txtidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 100, -1));
        jPanel1.add(txtredate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 130, -1));

        tbllend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbllend);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 361, 990, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void autoId(){
    try{
        String sql="SELECT `record_no` FROM `bookLend` ORDER BY record_no DESC LIMIT 1";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String rnno=rs.getString("record_no");
            int co=rnno.length();
            String txt=rnno.substring(0, 2);
            String num=rnno.substring(2, co);
            int n=Integer.parseInt(num);
            n++;
            String snum=Integer.toString(n);
            String ftxt=txt+snum;
            txtrno.setText(ftxt);
            
        }else
        {
            txtrno.setText("RN16111037");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
    
    private void txtmtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmtypeActionPerformed

    private void txtmidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmidKeyReleased
        try{
        String sql="SELECT `mid`, `name`, `type` FROM `addmember` WHERE mid='"+txtmid.getText()+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
           txtmname.setText(rs.getString("name"));
           txtmtype.setText(rs.getString("type"));
            
        }else{
            txtmname.setText("");
            txtmtype.setText("");
        }
    }//GEN-LAST:event_txtmidKeyReleased
 catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
    }
    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
         try{
        String sql="SELECT `name`, `book_type`FROM `addbook` WHERE bid='"+txtbid.getText()+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
           txtbname.setText(rs.getString("name"));
           txtbtype.setText(rs.getString("book_type"));
            
        }
        else{
            txtbname.setText("");
            txtbtype.setText("");
        }
    }                                  
 catch(Exception e)
    {
        JOptionPane.showMessageDialog(rootPane,e);
    }
         String btype=txtbtype.getText();
         
       if( btype.equals("Issue"))
       {
        LocalDate today=LocalDate.now();
        LocalDate reday=today.plus(10,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtredate.setText(reday.toString());
        
        
            
        }
       else
       {
           LocalDate today=LocalDate.now();
        LocalDate reday=today.plus(0,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtredate.setText(reday.toString());
         
       }
        tablelord();
    }//GEN-LAST:event_txtbidKeyReleased
 private void tablelord(){
     
        try{
            String sql="SELECT `record_no`, `mid`, `bid`, `i_date`, `r_date` FROM `booklend`";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            tbllend.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
          
          
        }catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);        }
    }
 private void clear(){
     txtbid.setText("");
     txtmid.setText("");
     txtbname.setText("");
     txtbtype.setText("");
     txtmname.setText("");
     txtmtype.setText("");
 }
 private void update(){
     try{
         String sql="UPDATE `addbook` SET mark='1'WHERE bid='"+txtbid.getText()+"'";
         pst=conn.prepareStatement(sql);
         pst.execute();
         JOptionPane.showMessageDialog(rootPane, "Update Success");
         tablelord();
     }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane,e);
     }
 }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        String rno=txtrno.getText();
        String mid=txtmid.getText();
        String bid=txtbid.getText();
        String idate=txtidate.getText();
        String rdate=txtredate.getText();
        try{
           
           String sql="INSERT INTO `booklend`(`record_no`, `mid`, `bid`, `i_date`, `r_date`,mark) VALUES('"+rno+"','"+mid+"','"+bid+"','"+idate+"','"+rdate+"','0')";
           PreparedStatement pst=conn.prepareStatement(sql);
           pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully insert");
            
            
            // number of remain copies are updated by one;
            
       }catch(Exception e)
               {
                   JOptionPane.showMessageDialog(rootPane, e);
               }
        
        update();
        tablelord();
        clear();
        autoId();
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllend;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtbtype;
    private javax.swing.JTextField txtidate;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmtype;
    private javax.swing.JTextField txtredate;
    private javax.swing.JTextField txtrno;
    // End of variables declaration//GEN-END:variables
}
