/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Return extends javax.swing.JInternalFrame {

    /**
     * Creates new form Return
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Return() {
        initComponents();
         conn=DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        txtlateday = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1020, 560));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 660));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1040, 70));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 490, 380));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 270, 380));

        jButton1.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 490, 30));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel6.setText("Book ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel7.setText("Member ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel8.setText("Late days");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel9.setText("Fine");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 80, -1));

        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 180, -1));
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, -1));
        jPanel1.add(txtlateday, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 180, -1));
        jPanel1.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 180, -1));

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 250, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
        
          try{
        String sql="SELECT `mid`, `r_date`FROM `booklend` WHERE bid='"+txtbid.getText()+"' and mark='0'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
           txtmid.setText(rs.getString("mid"));
           String r_date=rs.getString("r_date");
           LocalDate today=LocalDate.now();
           LocalDate rday=LocalDate.parse(r_date);
           
           Long day_gap=ChronoUnit.DAYS.between(rday, today);
           if(day_gap>0){
               
           
           
          txtlateday.setText(day_gap.toString());
          Long fine=10*day_gap;
          txtfine.setText(String.valueOf(fine));
           }
           else{
               txtlateday.setText("0");
               txtfine.setText("0");
           }
        }
        
    }                                  
 catch(Exception e)
    {
       // JOptionPane.showMessageDialog(rootPane,e);
    }
    }//GEN-LAST:event_txtbidKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String bid=txtbid.getText();
        String mid=txtmid.getText();
        String ldate=txtlateday.getText();
        String fine=txtfine.getText();
                
          try{
           
           String sql="INSERT INTO `bookreturn`(`bid`, `mid`, `late_days`, `fine`) VALUES('"+bid+"','"+mid+"','"+ldate+"','"+fine+"')";
           PreparedStatement pst=conn.prepareStatement(sql);
           pst.execute();
           update();
           bill();
           retunMark();
            JOptionPane.showMessageDialog(rootPane, "Successfully insert");
       }catch(Exception e)
               {
                   JOptionPane.showMessageDialog(rootPane, e);
               }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bill()
    {
        txtbill.setText(
                "Library Name: "+"BOOK HUB"+"\n"
               + "No of Date: "+txtlateday.getText()+"\n"
                +"Amount: "+txtfine.getText()
        );
        
        
    }
    
    
    private void update(){
     try{
         String sql="UPDATE `addbook` SET `mark`='0' WHERE bid='"+txtbid.getText()+"'";
         pst=conn.prepareStatement(sql);
         pst.execute();
        // JOptionPane.showMessageDialog(rootPane, "Update Success");
         
     }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane,e);
     }
 }
    private void retunMark(){
     try{
         String sql="UPDATE `booklend` SET `mark`='1' WHERE bid='"+txtbid.getText()+"'";
         pst=conn.prepareStatement(sql);
         pst.execute();
        // JOptionPane.showMessageDialog(rootPane, "Update Success");
         
     }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane,e);
     }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtlateday;
    private javax.swing.JTextField txtmid;
    // End of variables declaration//GEN-END:variables
}
