/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static java.awt.event.PaintEvent.UPDATE;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.runtime.PropertyDescriptor.SET;

/**
 *
 * @author Lenovo
 */
public class AddBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBook
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public AddBook() {
        initComponents();
        conn=DBConnect.connect();
        autoId();
        tablelord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtbCode = new javax.swing.JTextField();
        txtcopies = new javax.swing.JTextField();
        txtpub = new javax.swing.JTextField();
        cmbtype = new javax.swing.JComboBox();
        cmbcategory = new javax.swing.JComboBox();
        datebath = new com.toedter.calendar.JDateChooser();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 50));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel5.setText("Book Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, 110, 30));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 130, 110, 30));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel7.setText("B Code");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 180, 110, 30));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 210, 50, 20));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setText("Category");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel10.setText("Book Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setText("Publisher");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 136, -1, 50));
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, -1));
        jPanel1.add(txtbCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 210, -1));
        jPanel1.add(txtcopies, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 210, -1));
        jPanel1.add(txtpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 210, -1));

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Issue", "Read Only", " " }));
        jPanel1.add(cmbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 200, 30));

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Computer", "E&TC", "Civil", "Mechanical" }));
        jPanel1.add(cmbcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, -1));
        jPanel1.add(datebath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 210, -1));

        btnadd.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 160, 30));

        btnupdate.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 160, 30));

        btndelete.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 160, 30));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 25)); // NOI18N
        jLabel14.setText("Books");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1000, 220));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1020, 560));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 630));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setText("Copies");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 221, 80, 40));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 950, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1056, 673);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       String bid=txtbid.getText();
       String name=txtname.getText();
       String bcode=txtbCode.getText();
       String date=((JTextField)datebath.getDateEditor().getUiComponent()).getText();
       String category=cmbcategory.getSelectedItem().toString();
       String btype=cmbtype.getSelectedItem().toString();
       String pub=txtpub.getText();
      // String rem=txtremain.getText();
       String copies=txtcopies.getText();
       
    
       
       try{
           
           String sql="INSERT INTO `addbook`(`bid`, `name`, `b_code`, `date`, `category`, `book_type`, `publisher`, `Copies`,mark)VALUES('"+bid+"','"+name+"','"+bcode+"','"+date+"','"+category+"','"+btype+"','"+pub+"','"+copies+"','0')";
           PreparedStatement pst=conn.prepareStatement(sql);
           pst.execute();
           
      
           
            JOptionPane.showMessageDialog(rootPane, "Successfully insert");
       }catch(Exception e)
               {
                   JOptionPane.showMessageDialog(rootPane, e);
               }
        clearFild();
        autoId();
       tablelord();
      
        
            
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked
private void clearFild()
{
   // txtbid.setText("");
    txtname.setText("");
    txtbCode.setText("");
    ((JTextField)datebath.getDateEditor().getUiComponent()).setText("");
    cmbcategory.setSelectedIndex(0);
    cmbtype.setSelectedIndex(0);
    txtpub.setText("");
   // txtremain.setText("");
    txtcopies.setText("");
}
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       String bid=txtbid.getText();
       String name=txtname.getText();
       String bcode=txtbCode.getText();
       String date=((JTextField)datebath.getDateEditor().getUiComponent()).getText();
       String category=cmbcategory.getSelectedItem().toString();
       String btype=cmbtype.getSelectedItem().toString();
       String pub=txtpub.getText();
     //  String rem=txtremain.getText();
       String copies=txtcopies.getText();
        try{
      String sql = "UPDATE `addbook` SET `name`='"+name+"',`b_code`='"+bcode+"',`date`='"+date+"',`category`='"+category+"',`book_type`='"+btype+"',`publisher`='"+pub+"',`Copies`='"+copies+"' WHERE `bid`='"+bid+"' ";
      pst=conn.prepareStatement(sql);
      pst.execute();
      JOptionPane.showMessageDialog(rootPane, "update success");
       tablelord();
            clearFild();
      }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
            String sql="DELETE FROM `addbook` WHERE bid='"+txtbid.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Delete success");
            tablelord();
             
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
             clearFild();
    }//GEN-LAST:event_btndeleteActionPerformed
  private void tablelord(){
        try{
            String sql="SELECT `bid`, `name`, `b_code`, `date`, `category`, `book_type`, `publisher`, `Copies` FROM `addbook`";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

           // tbldetails.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
          
          
        }catch(Exception e)
        {
            JOptionPane.showConfirmDialog(rootPane, e);        }
    }
    private void autoId(){
    try{
        String sql="SELECT `bid` FROM `addbook` ORDER BY bid DESC LIMIT 1";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
            String rnno=rs.getString("bid");
            int co=rnno.length();
            String txt=rnno.substring(0, 2);
            String num=rnno.substring(2, co);
            int n=Integer.parseInt(num);
            n++;
            String snum=Integer.toString(n);
            String ftxt=txt+snum;
            txtbid.setText(ftxt);
            
        }else
        {
            txtbid.setText("B11000");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbcategory;
    private javax.swing.JComboBox cmbtype;
    private com.toedter.calendar.JDateChooser datebath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbCode;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtcopies;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpub;
    // End of variables declaration//GEN-END:variables
}
